name: Build alpine-apache Docker image
env:
  IMAGE_BASE: docker.io/kanstin/alpine-apache

on:
  workflow_dispatch:
    inputs:
      do_publish:
        description: "Publish image after build?"
        required: true
        type: boolean
        default: false
      apache_version:
        description: "The version of Apache httpd to include in the image."
        required: true
        type: string
        default: "2.4.63"

jobs:
  build-push-amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up tags
        run: |
          echo "LATEST_TAG=${IMAGE_BASE}:latest" >> $GITHUB_ENV
          echo "VERSION_TAG=${IMAGE_BASE}:${{ inputs.apache_version }}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:alpine-apache"
          build-args: |
            BASE_VERSION=${{ inputs.apache_version }}
          push: |
            ${{ github.event_name == 'workflow_dispatch' && inputs.do_publish == true
             || github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.LATEST_TAG }}-amd64
            ${{ env.VERSION_TAG }}-amd64
          cache-from: type=gha,scope=amd64
          cache-to: type=gha,mode=max,scope=amd64

  build-push-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up tags
        run: |
          echo "LATEST_TAG=${IMAGE_BASE}:latest" >> $GITHUB_ENV
          echo "VERSION_TAG=${IMAGE_BASE}:${{ inputs.apache_version }}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:alpine-fips"
          build-args: |
            BASE_VERSION=${{ inputs.apache_version }}
          push: |
            ${{ github.event_name == 'workflow_dispatch' && inputs.do_publish == true
             || github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.LATEST_TAG }}-arm64
            ${{ env.VERSION_TAG }}-arm64
          cache-from: type=gha,scope=arm64
          cache-to: type=gha,mode=max,scope=arm64

  create-push-manifests:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    needs: [build-push-arm64, build-push-amd64]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up tags
        run: |
          echo "LATEST_TAG=${IMAGE_BASE}:latest" >> $GITHUB_ENV
          echo "VERSION_TAG=${IMAGE_BASE}:${{ inputs.apache_version }}" >> $GITHUB_ENV

      - name: Create manifests and push
        run: |
          arm64sha=$(docker manifest inspect ${{ env.LATEST_TAG }}-arm64 \
            | jq -r '.manifests[] | select(.platform.architecture == "arm64") | .digest')
          amd64sha=$(docker manifest inspect ${{ env.LATEST_TAG }}-amd64 \
            | jq -r '.manifests[] | select(.platform.architecture == "amd64") | .digest')
          docker manifest create ${{ env.LATEST_TAG }} \
            ${{ env.IMAGE_BASE }}@$arm64sha \
            ${{ env.IMAGE_BASE }}@$amd64sha
          docker manifest push -p ${{ env.LATEST_TAG }}
          docker manifest create ${{ env.VERSION_TAG }} \
            ${{ env.IMAGE_BASE }}@$arm64sha \
            ${{ env.IMAGE_BASE }}@$amd64sha
          docker manifest push -p ${{ env.VERSION_TAG }}

